### ISSUE TITLE
Unary operator expected

### ISSUE THREAD

**Issue by mobileben** [faithfracture/Apple-Boost-BuildScript#13]
As an FYI, I have pulled the latest and this this warning. Not sure if this is expected or not:

Bootstrapping for iOS (with libs atomic,chrono,container,date_time,exception,fiber,filesystem,graph,graph_parallel,iostreams,locale,log,metaparse,,program_options,python,random,regex,serialization,signals,system,test,thread,timer,type_erasure,wave)
./bootstrap.sh: line 90: test: =: unary operator expected

The command I used with

./boost.sh -ios --boost-libs all --no-framework

**Comment by faithfracture** [comment]
This is being caused by the same thing that's causing all of the fatal lipo errors reported in #14.
