### ISSUE TITLE
building iostreams (missing objects)

### ISSUE THREAD

**Issue by liran999** [faithfracture/Apple-Boost-BuildScript#17]
hey guys !
i'm trying to build iostreams for ios using this script ...
i have added iostreams to BOOST_LIBS and i was able to build iostream, BUT...
it seams that the static lib i got is missing some objects.. for example zlib, gzip ....
can i do anything about that ?

thanks !!!!

**Comment by faithfracture** [comment]
I'll start with stating that I don't use iostreams, so the rest of this is just a guess.

Boost itself doesn't include gzip, zlib, etc, so the fact that the resulting static library file doesn't include them isn't surprising. Looking at one of the comments from [https://stackoverflow.com/questions/7282645/how-to-build-boost-iostreams-with-gzip-and-bzip2-support-on-windows](url), it seems that you can get Boost to link to zlib & gzip by adding an environment variable (or setting one in the current shell) prior to executing the script. That seems to be the easiest option. The other one would require a modification to the build script to provide include paths to the missing libraries for the linker.

Making the script change is totally doable, but unless you have an undetermined amount of time to wait on me to do it, you'll be better off trying the first solution (or making the modification yourself).

**Comment by liran999** [comment]
thank you so much man, the ZLIB_SOURCE environment variable worked !

**Comment by faithfracture** [comment]
Awesome, thanks for the update. I'll add some documentation about that in case anyone else has the same problem.

**Comment by deshan** [comment]
@faithfracture 
Thanks for this. Saved lot of time.

Need help here with iostream with zlib.

> thank you so much man, the ZLIB_SOURCE environment variable worked !

In my case this gave me compile errors.
error: invalid argument '-std=c++14' not allowed with 'C'

below is the build log.
[ios-build.log](https://github.com/faithfracture/Apple-Boost-BuildScript/files/6873848/ios-build.log)

Thanks

**Comment by deshan** [comment]
With below managed to fix, for anyone needs it

1. Setting environment var ZLIB_SOURCE=....
2. In boost.sh remove -std and -stdlib options from OTHER_FLAGS
3. May need to run  ./configure inside zlib source
