### ISSUE TITLE
Cannot build for tvOS with Xcode 9

### ISSUE THREAD

**Issue by faithfracture** [faithfracture/Apple-Boost-BuildScript#20]
Building for tvOS fails with a bunch of errors about members of `cmath` not being  in the global namespace.

Building works fine still for iOS and macOS.

Probably an issue with include path configuration.

**Comment by finddit** [comment]
I'm also having the same issue. Would it be possible to fix this? Alternatively I will try to look into the issue.

**Comment by faithfracture** [comment]
Yeah. I've got a tvOS project coming up shortly, so I'll be forced to figure it out. I'm not scheduled to start on that project for a month or so though. I'm not sure that I'll have time to put into this until then though. In the meantime, I _think_ you can download Xcode 8 and switch the CLI with xcode-select (I believe I tried this, but it's been a while so I'm not 100% sure).
