### ISSUE TITLE
boost.sh -ios --boost-version 1.67.0 --boost-libs all  get error: unknown wrapper compiler mpic++

### ISSUE THREAD

**Issue by ludaye123** [faithfracture/Apple-Boost-BuildScript#28]
MPI auto-detection failed: unknown wrapper compiler mpic++
Please report this error to the Boost mailing list: http://www.boost.org
You will need to manually configure MPI support.
error: wrong library name 'metaparse' in the --with-<library> option.

Has somebody else encountered the same error? Could somebody give some  
hint? Btw.

**Comment by faithfracture** [comment]
Please don't open two issues for the same problem.
