### ISSUE TITLE
Building fails if Xcode is renamed with space in the name

### ISSUE THREAD

**Issue by jterhorst** [faithfracture/Apple-Boost-BuildScript#34]
Sometimes I'll rename `Xcode.app` to `Xcode 9.4.app`. If I do this, the script fails to build, presumably because of spaces in the path. Renaming it back to `Xcode.app` and resetting everything fixes it. Is it possible to support spaces in `XCODE_PATH`?

**Comment by faithfracture** [comment]
Yeah, I'm sure that's doable. I don't typically use spaces in anything, just underscores. (e.g. Xcode.app => Xcode_9.4.app).

**Comment by faithfracture** [comment]
Closed by #46
