### ISSUE TITLE
Build for iOS does not produce framework

### ISSUE THREAD

**Issue by thomasdao** [faithfracture/Apple-Boost-BuildScript#39]
Hi, thanks for the useful script!

I've tried run this command but it doesn't produce boost.framework file:
`./boost.sh -ios --boost-version 1.70.0 --boost-libs "date_time regex system thread" --min-ios-version 11.0`

Running the build for macOS can produce the framework fine:
`./boost.sh -macos --boost-version 1.70.0 --boost-libs "date_time regex system thread" --min-macos-version 10.11 --macos-archs "i386 x86_64"`

Not sure if I need to do something else. My Xcode is `10.2.1`, my system is Mac `10.14.5`.

Thanks :)

**Comment by faithfracture** [comment]
Does it produce _anything_ useful? Check the log file (`build/boost/1.70.0/ios/release/ios-build.log`). When I try to run it I'm getting `clang: error: invalid iOS deployment version '-miphoneos-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]` (near the bottom of the log file), which suggest that the `--min-ios-version` flag isn't working correctly. Let me know if you see the same thing & I'll address that. If you have a different error let me know.


You could also just post the contents of the log file inside a details block, like this:
```
<details><summary>Log File</summary>
-- paste log file contents here --
</details>
```
Which turns into this:
<details><summary>Log File</summary>
-- paste log file contents here --
</details>

**Comment by thomasdao** [comment]
@faithfracture: thanks for the reply :), the script can produce `prefix` folder with contents inside. I also see the same error that you got (`error: invalid iOS deployment version '-miphoneos-version-min=11.0', iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]`).

**Comment by faithfracture** [comment]
Ok great, thanks for verifying that. Now I know what to work on :)

**Comment by faithfracture** [comment]
Just pushed a fix. Let me know if you have any other problems.

FYI, I updated the default min iOS version to 11, so you don't need to pass that flag anymore (unless you want a different min iOS version of course...)

**Comment by thomasdao** [comment]
Thanks so much for the fix. The framework is now produced for me.
