### ISSUE TITLE
SDK cannot be located

### ISSUE THREAD

**Issue by DZoki019** [faithfracture/Apple-Boost-BuildScript#44]
Clean installed Catalina, Xcode and I got error when I wanted to build boost library with command:

`./boost.sh -ios -macos --ios-archs "armv7 armv7s arm64 arm64e" --min-ios-version 10.3 --universal`
```
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: SDK "iphoneos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'iphoneos'
xcrun: error: SDK "appletvos" cannot be located
xcrun: error: SDK "appletvos" cannot be located
xcrun: error: unable to lookup item 'SDKVersion' in SDK 'appletvos'
xcrun: error: SDK "appletvos" cannot be located
xcrun: error: SDK "appletvos" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'appletvos'
xcrun: error: SDK "appletvsimulator" cannot be located
xcrun: error: SDK "appletvsimulator" cannot be located
xcrun: error: unable to lookup item 'Path' in SDK 'appletvsimulator'
```

Then I found an issue where command:
`xcode-select -print-path`
returns: 
`/Library/Developer/CommandLineTools`
instead of:
`/Applications/Xcode.app/Contents/Developer`

Changed root folder with command:
`sudo xcode-select -s /Applications/Xcode.app/Contents/Developer`

After that everything is fine.

**Comment by faithfracture** [comment]
I didn’t run into that with just the upgrade. Thanks for the heads up with a clean install.
