### ISSUE TITLE
Xcode 11.4 unknown argument: '-fcoalesce-templates'

### ISSUE THREAD

**Issue by RGPaul** [faithfracture/Apple-Boost-BuildScript#45]
After Updating to Xcode 11.4 I get the following error while compiling for macOS or iOS:
`clang: error: unknown argument: '-fcoalesce-templates'`

Anyone have an idea what might be the problem?

**Comment by faithfracture** [comment]
I'm seeing that too. Looks like a compiler flag is getting set somewhere that shouldn't be. It's not being added in the script itself, and since Clang is complaining about it I'm going to assume it's coming from Boost. I'll look into it.

**Comment by mjpan** [comment]
I found a patch on apache/kudu which fixes this issue, for boost 1.69.0.  apply the patch allows me to build the framework for ios, which is what I need.  building macosx is still broken, although for a different reason.
https://github.com/apache/kudu/commit/e6fa761a4a60118bb61883fe8342943253f350d2#diff-d424359aa013fc54d17b0ecb4c6d52bc

**Comment by faithfracture** [comment]
Looks like https://github.com/boostorg/build/pull/560 fixes this - we'll need to update the script to conditionally apply this patch until that PR is included in a Boost release.
