### ISSUE TITLE
Accepting pull requests?

### ISSUE THREAD

**Issue by guillaumealgis** [faithfracture/Apple-Boost-BuildScript#46]
Hi,

I spent the last few days working on this script in our fork (https://github.com/ipsosante/Apple-Boost-BuildScript) to make it work for us. I'd be happy to upstream some of our fixes and improvements that would benefit more than just us, so I was wondering if you were accepting PR / had the time to review them?

Some of the changes are :

- Fix warnings and errors detected by [shellcheck](https://github.com/koalaman/shellcheck)
- Fix https://github.com/faithfracture/Apple-Boost-BuildScript/issues/45 by automatically patching boost
- Fix https://github.com/faithfracture/Apple-Boost-BuildScript/issues/34
- Use [bcp](https://www.boost.org/doc/libs/1_69_0/tools/bcp/doc/html/index.html) to reduce the resulting framework size
- Cleanup the custom b2 toolsets used
- Add function to build a [XCFramework](https://developer.apple.com/videos/play/wwdc2019/416/)

Let me know if you're interested and I'll send PR your way :)

**Comment by faithfracture** [comment]
Yes please that sounds great! I really only get around to maintaining this myself when we updated our Boost version, and we’ve been on 1.69 for a while now. Being quarantined and all right now, I’m finding myself with a little extra time, so now would be a great time to submit PRs :)

I would app appreciate it if you wouldn’t mind submitting them separately in case there’s things about one or another I’d like to dialog about.

Thanks!

**Comment by guillaumealgis** [comment]
> I really only get around to maintaining this myself when we updated our Boost version

Same :)

> I would app appreciate it if you wouldn’t mind submitting them separately in case there’s things about one or another I’d like to dialog about.

Sure, that's what I had in mind too. I'll get to it then!
