### ISSUE TITLE
Boost built and ready for iOS/macOS (repo)

### ISSUE THREAD

**Issue by blazorin** [faithfracture/Apple-Boost-BuildScript#75]
### I've made a [repository](https://github.com/blazorin/EssentialLibs) which contains Boost and OpenSSL built and ready for iOS and macOS architectures.

**Includes thread-safe libraries aswell!**

If possible, do not close this issue, just trying to help!

**Comment by kambala-decapitator** [comment]
sharing your build scripts and not just binaries would be great

**Comment by guillaumealgis** [comment]
I'm sorry @blazorin but I'll close this as this is not an "issue" with Apple-Boost-BuildScript, and issues are not meant for self-promotion.

Also, while I don't doubt you are meaning well, **I would not recommend anyone to embed pre-built binaries from an unknown vendor (you) in a program**, particularly when said binaries are for cryptographic / security purposes (OpenSSL lib).
