### ISSUE TITLE
Not clear how to pass array to --boost-libs or --ios-archs

### ISSUE THREAD

**Issue by kyzmitch** [faithfracture/Apple-Boost-BuildScript#79]
From the docs it should be the following format and it doesn't work for me:
```
--ios-archs "(archs, ...)"
--boost-libs "{all|none|(lib, ...)}"
```
I was able to pass parameters only with following format `--ios-archs`:
```
--ios-archs "armv7 arm64"
```

and the same format didn't work for `--boost-libs` parameter. Single arguments worked fine: 
```
--boost-libs thread
```

**Comment by kambala-decapitator** [comment]
Space-separated list of libs works fine too, see an example at https://github.com/kambala-decapitator/vcmi-ios-depends/blob/main/deps/boost.sh

**Comment by kyzmitch** [comment]
thanks for reply, for some reason following command doesn't work and it prints help:
```
./boost.sh --min-ios-version 10.0 -ios --boost-version 1.80.0 --boost-libs ‘system date_time thread’ --no-framework --no-thinning --universal --ios-archs "arm64 armv7"
```

**Comment by kyzmitch** [comment]
following format works for me, just would be good to update help command to provide actual examples if it is possible, I could add it to my PR which is about different thing actually https://github.com/faithfracture/Apple-Boost-BuildScript/pull/78
```
./boost.sh --min-ios-version 10.0 -ios --boost-version 1.80.0 --boost-libs 'system date_time thread' --no-framework --no-thinning --universal --ios-archs "arm64 armv7"
```

**Comment by kambala-decapitator** [comment]
> maybe quote symbol is wrong

It definitely is :) compare your `‘` to the standard `'`

**Comment by kambala-decapitator** [comment]
You can also escape spaces with backslash instead of using quotes:

    --boost-libs lib1\ lib2

**Comment by guillaumealgis** [comment]
> following format works for me, just would be good to update help command to provide actual examples if it is possible

Thanks for the feedback @kyzmitch , I've added examples for `--boost-libs` and `--ios-archs` to the script's help 👍🏻
