### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ygx2011** [faithfracture/Apple-Boost-BuildScript#9]
Hello,

I got a problem like this,

Undefined symbols for architecture arm64:
"typeinfo for boost::archive::detail::basic_pointer_oserializer", referenced from:

and I used serialization libraries with LLVM 8.0 - c++, any solutions for this?

Thank you.

**Comment by faithfracture** [comment]
Can you post the parameters you are using when running the script?

The serialization library is not built with this script by default. You need to be sure to override the default libraries by passing `serialization` option to the `--boost-libs` (along with whatever other libraries you need built), or by manually editing the `BOOST_LIBS` variable at the top of the script.

**Comment by ygx2011** [comment]
Thank you, I found that yesterday, and I added serialization option to the script, it worked.

**Comment by faithfracture** [comment]
Awesome!

**Comment by velthune** [comment]
I had same problem with boost thread library, I run the script in this way and all works great:

    ./boost.sh -ios --boost-version 1.70.0 --boost-libs thread
